---
# role: ansible-role-nfs
# file: tasks/server.yml

- name: "Install NFS server packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ nfs_server_packages }}"

- name: "Create NFS mountpoints"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nfs_exports[item].owner }}"
    group: "{{ nfs_exports[item].group }}"
    mode: "{{ nfs_exports[item].mode }}"
    modification_time: preserve
    access_time: preserve
  loop: "{{ nfs_exports | flatten(levels=1) }}"

- name: "Configure /etc/exports"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    mode: '0640'
  loop: ['etc/exports']
  notify: Restart NFS

# This only affects NFS < v4 and should be disabled
- name: "Enable {{ rpcbind_service }}"
  ansible.builtin.service:
    name: "{{ rpcbind_service }}"
    enabled: "{{ nfs_rpcbind_enabled | bool }}"

- name: "Enable {{ nfs_service }}"
  ansible.builtin.service:
    name: "{{ nfs_service }}"
    enabled: true
