---
# role: ansible-role-nfs
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: nfs-default
    image: ${MOLECULE_DIST:-"jam82/ubuntu-molecule:18.04"}
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  playbooks:
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        role_nfs_enabled: true
        nfs_server: true
        nfs_client: true
        nfs_exports:
          '/srv/nfs_export1':
            owner: root
            group: root
            mode: '0750'
            hosts:
              127.0.0.1:
                - rw
                - async
                - no_subtree_check
                - secure
              127.0.0.2:
                - rw
                - sync
                - secure
          '/srv/nfs_export2':
            owner: root
            group: root
            mode: '0750'
            hosts:
              127.0.0.1:
                - r
                - async
                - no_subtree_check
                - secure
scenario:
  name: default
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: true
    sudo: true
  lint:
    name: flake8
