---
# role: ansible-role-nfs
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 1024
      cpus: 1
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: nfs-arch
    box: "archlinux/archlinux"
  - name: nfs-centos7
    box: "centos/7"
  - name: nfs-debian9
    box: "debian/stretch64"
  - name: nfs-ubuntu1804
    box: "generic/ubuntu1804"
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        role_nfs_enabled: true
        nfs_server: true
        nfs_client: true
        nfs_exports:
          '/srv/nfs_export1':
            owner: root
            group: root
            mode: '0750'
            hosts:
              127.0.0.1:
                - rw
                - async
                - no_subtree_check
                - secure
              127.0.0.2:
                - rw
                - sync
                - secure
          '/srv/nfs_export2':
            owner: root
            group: root
            mode: '0750'
            hosts:
              127.0.0.1:
                - r
                - async
                - no_subtree_check
                - secure
scenario:
  name: kvm
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: true
    sudo: true
  lint:
    name: flake8
